import Head from 'next/head'
import { motion } from 'framer-motion';


const textVariants = {
  hidden: {
    y: '100vh',
    x: '-100vw',
    opacity: 0,
  },
  visible: {
    y: 0,
    x: 0,
    opacity: 1,
    transition: {
      duration: 2,
    }
  }
}

const starsVariants = {
  hidden: {
    x: '-100vw',
    y: '-80vh',
    opacity: 0,
  },
  visible: {
    x: 0,
    y: '20vh',
    opacity: 1,
    transition: {
      repeat: Infinity,
      duration: 5,
    }
  }
}


export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto Shuttle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center min-h-screen">
        <section className="relative w-full h-screen flex items-center justify-center overflow-hidden">
          <motion.img variants={textVariants} initial='hidden' animate='visible' src="./rocket.png"
            className="background-image max-h-screen bottom-0 z-50 clip-background text-background_mood-dark" />
          <motion.img src="./stars.png" variants={starsVariants} initial='hidden' animate='visible'
            className="background-image max-h-screen -bottom-14 z-50 clip-background text-background_mood-dark" />
        </section>
      </main>
    </div>
  )
}
